name: CD

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test

  publish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/publish
        with:
          dry-run: false
