name: CD

on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    uses: ./.github/actions/lint.yml

  test:
    uses: ./.github/actions/test.yml

  publish:
    needs: [lint, test]
    uses: ./.github/actions/publish.yml
    with:
      dry-run: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
