name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/actions/lint.yml

  test:
    uses: ./.github/actions/test.yml

  publish-dry-run:
    needs: [lint, test]
    uses: ./.github/actions/publish.yml
    with:
      dry-run: true
