name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test

  publish-dry-run:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/publish
        with:
          dry-run: true
